const API_URL = "https://api.deepinfra.com/v1/openai/chat/completions";
const MODEL = "openai/gpt-oss-20b";

const getApiKey = () => import.meta.env.VITE_DEEPINFRA_API_KEY || "";

const cleanResponse = (text) => {
  return text.trim()
    .replace(/^```mermaid\s*/, '')
    .replace(/^```\s*/, '')
    .replace(/```$/, '');
};

const callAI = async (messages) => {
  const apiKey = getApiKey();
  
  const payload = {
    model: MODEL,
    messages: messages,
    temperature: 0.2,
    stream: false
  };

  const headers = {
    "Content-Type": "application/json",
    "Authorization": apiKey ? `Bearer ${apiKey}` : ""
  };

  try {
    const response = await fetch(API_URL, {
      method: "POST",
      headers: headers,
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API Error ${response.status}: ${errorText}`);
    }

    const result = await response.json();
    
    if (result.choices && result.choices.length > 0) {
      return cleanResponse(result.choices[0].message.content);
    } else {
      throw new Error("Unexpected API response format");
    }
  } catch (err) {
    console.error("AI Request failed:", err);
    throw err;
  }
};

/**
 * Uses AI to fix broken Mermaid code based on the error message.
 * @param {string} code - The broken Mermaid code.
 * @param {string} error - The error message generated by Mermaid.
 * @returns {Promise<string>} - The fixed Mermaid code.
 */
export const fixMermaidCode = async (code, error) => {
  const systemPrompt = 
    "You are an expert in Mermaid.js diagramming. " +
    "Your task is to fix broken Mermaid code based on the provided error message. " +
    "Return ONLY the corrected Mermaid code. Do not include markdown code blocks, " +
    "explanations, or conversational text. Just the raw code.";

  const userPrompt = `Here is the broken Mermaid code:\n\n${code}\n\nError message:\n${error}\n\nPlease fix it.`;

  return callAI([
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt }
  ]);
};

/**
 * Uses AI to modify/fix Mermaid code based on user instruction.
 * @param {string} code - The current Mermaid code.
 * @param {string} instruction - The user's instruction or description of what's wrong.
 * @returns {Promise<string>} - The updated Mermaid code.
 */
export const assistMermaidCode = async (code, instruction) => {
  const systemPrompt = 
    "You are an expert in Mermaid.js diagramming. " +
    "Your task is to modify the provided Mermaid code based on the user's instruction. " +
    "The user might describe a visual bug (e.g., 'arrow is broken') or ask for a change. " +
    "Analyze the code and the request, then return ONLY the updated/corrected Mermaid code. " +
    "Do not include markdown code blocks, explanations, or conversational text. Just the raw code.";

  const userPrompt = `Current Mermaid code:\n\n${code}\n\nUser Instruction:\n${instruction}\n\nPlease update the code accordingly.`;

  return callAI([
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt }
  ]);
};